#include <lvgl.h>
#include <TFT_eSPI.h>

// Include the layout definition generated by EEZ Studio
#include "src/ui/ui.h"

// Set these constants to match the dimensions of your physical display
#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240

TFT_eSPI tft = TFT_eSPI(SCREEN_WIDTH, SCREEN_HEIGHT); 

// LVGL 9 uses a byte array for the memory buffer instead of lv_color_t
#define DRAW_BUF_SIZE (SCREEN_WIDTH * SCREEN_HEIGHT / 10 * (LV_COLOR_DEPTH / 8))
uint8_t draw_buf[DRAW_BUF_SIZE];

// LVGL 9 Flush function: Transfers pixels to the hardware
void my_disp_flush(lv_display_t *disp, const lv_area_t *area, uint8_t *px_map) {
    uint32_t w = area->x2 - area->x1 + 1;
    uint32_t h = area->y2 - area->y1 + 1;

    tft.startWrite();
    tft.setAddrWindow(area->x1, area->y1, w, h);
    // Push the color data to the screen
    tft.pushColors((uint16_t *)px_map, w * h, true);
    tft.endWrite();

    // Tell LVGL we are done flushing
    lv_display_flush_ready(disp);
}

// LVGL 9 requires a custom tick callback to track time
static uint32_t my_tick(void) {
    return millis();
}

void setup() {
    Serial.begin(115200); 

    // Turn on and orient the screen hardware
    tft.begin();          
    tft.setRotation(1); 

    // Initialize core graphics engine
    lv_init();

    // Tell LVGL how to track time for animations and touches
    lv_tick_set_cb(my_tick);

    // Register the display in LVGL 9
    lv_display_t * disp = lv_display_create(SCREEN_WIDTH, SCREEN_HEIGHT);
    lv_display_set_flush_cb(disp, my_disp_flush);
    lv_display_set_buffers(disp, draw_buf, NULL, sizeof(draw_buf), LV_DISPLAY_RENDER_MODE_PARTIAL);

    // Call the structural visual entry point generated by EEZ Studio
    ui_init();
}

void loop() {
    // Execute scheduled task loops inside the graphical engine
    lv_timer_handler(); 
    delay(5);
}